### ISSUE TITLE
 ERROR  Failed to compile with 1 errors  

### ISSUE THREAD

**Issue by anuxs** [nuxt/example-hackernews#2]
ERROR  Failed to compile with 1 errors                                                                                         

This dependency was not found:

* ~store/api in ./~/._babel-loader@6.4.1@babel-loader/lib?{"presets":["vue-app"],"cacheDirectory":true}!./~/._vue-loader@11.3.4@vue-load
er/lib/selector.js?type=script&index=0!./components/ItemList.vue

To install it, you can run: npm install --save ~store/api

**Comment by Atinux** [comment]
Hi @anuxs 

Actually the repository is not ready yet.

**Comment by anuxs** [comment]
i alread run npm install .
